
/**
* CompteCourantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Thursday, October 3, 2024 7:53:47 PM WET
*/

public final class CompteCourantHolder implements org.omg.CORBA.portable.Streamable
{
  public CompteCourant value = null;

  public CompteCourantHolder ()
  {
  }

  public CompteCourantHolder (CompteCourant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CompteCourantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CompteCourantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CompteCourantHelper.type ();
  }

}
