
/**
* CompteCourantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Thursday, October 3, 2024 7:53:47 PM WET
*/

public interface CompteCourantOperations  extends CompteOperations
{
  boolean DecouvertAutorise ();
  void DecouvertAutorise (boolean newDecouvertAutorise);
} // interface CompteCourantOperations
