
/**
* CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Thursday, October 3, 2024 7:53:47 PM WET
*/

public interface CompteOperations 
{
  float lire_montant ();
  void crediter (float somme_credit);
  void debiter (float somme_debit);
} // interface CompteOperations
