
/**
* CompteEpargneHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Thursday, October 3, 2024 7:53:47 PM WET
*/

public final class CompteEpargneHolder implements org.omg.CORBA.portable.Streamable
{
  public CompteEpargne value = null;

  public CompteEpargneHolder ()
  {
  }

  public CompteEpargneHolder (CompteEpargne initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CompteEpargneHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CompteEpargneHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CompteEpargneHelper.type ();
  }

}
