
/**
* CompteCourant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Thursday, October 3, 2024 7:53:47 PM WET
*/

public interface CompteCourant extends CompteCourantOperations, Compte, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompteCourant
