
/**
* CompteEpargneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Thursday, October 3, 2024 7:53:47 PM WET
*/

public interface CompteEpargneOperations  extends CompteOperations
{
  int taux ();
  void taux (int newTaux);
} // interface CompteEpargneOperations
